name: CombatProtector
main: com.tetra.combatprotector.CombatProtector
version: 2.7.2rb
description: Prevent players from logging out/teleporting in combat.
commands:
   combatlist:
      description: Checks a players gamemode.
      permission: combatprotector.combatlist
      usage: /combatlist
   cblog:
      description: Displays the combat damage history.
      permissions: combatprotector.cblog
      usage: /cblog [on;off]
   cstream:
     description: Stream's a players incoming and outgoing damage to sender.
     permissions: combatprotector.cstream
     usage: /cstream <playername>
authors: [Mastershake71]